site:
  title: TED Developer Documentation
  url: https://docs.ted.europa.eu
  start_page: home::index.adoc
content:
  edit_url: false
  sources:
  - url: https://github.com/OP-TED/OP-TED.github.io.git
    start_path: content
    branches: master
  - url: https://github.com/OP-TED/eForms-SDK.git
    start_path: docs
    branches: main
  - url: https://github.com/OP-TED/epo-docs.git
    start_path: ascii_doc
    branches:
    - main
    tags:
    - v*
  # - url: https://github.com/OP-TED/ESPD-EDM.git
  #   start_path: docs/src/main/asciidoc
  #   branches: []
  #   tags: v*
  - url: https://github.com/OP-TED/espd-docs.git
    start_path: /
    branches: master, v1.0.2, v2.0.0, v2.0.1, v2.0.2, v2.1.0, v2.1.1, v3.0.0 
    # tags: v2.1.1, v2.1.0, v2.0.2, v2.0.1, v2.0.0, v1.0.2, v1.0.1
ui:
  bundle:
    url: https://github.com/OP-TED/antora-eui/releases/download/ui-bundle/eForms-SDK-customisations/ui-bundle.zip
    snapshot: true
  supplemental_files: ./content/supplemental-ui
