site:
  title: TED Developer Documentation
  url: https://docs.ted.europa.eu
  start_page: home::index.adoc
content:
  edit_url: false
  sources:
  - url: https://github.com/OP-TED/OP-TED.github.io.git
    start_path: content
    branches: master
  - url: https://github.com/OP-TED/eforms-docs.git
    start_path: /
    branches: 0.2.x, 0.3.x
  - url: https://github.com/OP-TED/epo-docs.git
    start_path: ascii_doc
    branches:
    - main
    tags:
    - v*
  - url: https://github.com/OP-TED/espd-docs.git
    start_path: /
    branches: v1.0.1, v1.0.2, v2.0.0, v2.0.1, v2.0.2, v2.1.0, v2.1.1, v3.0.0 
ui:
  bundle:
    url: https://github.com/OP-TED/antora-eui/releases/download/ui-bundle/eForms-SDK-customisations/ui-bundle.zip
    snapshot: true
  supplemental_files: ./content/supplemental-ui
