:doctitle: Reflective Writing

== Description

The Reflective Writing assignment was one of the last assignments in the programme and consisted of writing one reflection of between 600 and 800 words on #add topic list#. The aim of the assignment was to #add aim#.
////
As a result of studying this programme, I got a job in technical writing that involves redesigning information and managing updates to a static documentation website: #TED-OP Developer Docs#. The website is a resource for developers who are implementing APIs, data production or consumption, or tools to do with EProcurement in the EU. The website is built using Antora and Asciidoc. Some sections have been fundamentally redesigned and some parts are still scheduled for redesign.
////

== Reflection

=== Why I chose the Reflective Writing assignment

I received this assignment with some dread because it is not something I generally do and usually don't have or prioritise time for. Apart from not really having a choice, I chose this assignment here as I accepted that I should try it and see if it brought me the benefit that it brings others. I was surprised to enjoy it more than I had anticipated, but have mixed feelings as to whether it was of benefit to me.

=== Which skills were demonstrated
The skills demonstrated were the ability to consider and analyse pros and cons of the topic and evaluate  a technology or how much I have learnt.

