name: TED Developer Docs

on:
  workflow_dispatch:
  push:
    branches: 
      - master

jobs:
  publish_site:
    name: "Build and publish site with Antora"
    runs-on: [ubuntu-latest]
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      NODE_OPTIONS: '--max-old-space-size=8192'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v2
        with:
          version: 16

      - name: Install Corepack
        run: npm install --prefix .node corepack

      - name: Install Yarn
        run: .node/node_modules/.bin/corepack enable --install-directory .node

      - name: Install packages
        run: .node/yarn install

      - name: Generate site
        run: yarn run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          # ACCESS_TOKEN: # optional
          TOKEN: "${{ github.token}}"
          FOLDER: build/site
          BRANCH: 'gh-pages'
          COMMIT-MESSAGE: "[CI] Publish Documentation for ${{ github.sha }}"

  index_site:
    name: "Index site using Docsearch Crawler"
    needs: publish_site
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get the content of docsearch-config.json as config
        id: docsearch_config
        run: echo "docsearch_config=$(cat config/docsearch-config.json | jq -r tostring)" >> $GITHUB_ENV

      - name: Push indices to Algolia
        uses: signcl/docsearch-scraper-action@master
        env:
          APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
          API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          CONFIG: ${{ env.docsearch_config }}
